# Basic Python

## 1. Split this string

In [ ]:
s = "Hi there Sam!"

In [1]:
s = "Hi there Sam!"
x = s.split()
print(x)

['Hi', 'there', 'Sam!']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [3]:
planet = "Earth"
diameter = 12742

In [2]:
planet = "Earth"
diameter = 12742
print('the diameter of earth is 12742 kilometers.' .format(planet,diameter));

the diameter of earth is 12742 kilometers.


## 3. In this nest dictionary grab the word "hello"

In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [4]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
print(d['k1'][3]["tricky"][3]['target'][3])

hello


# Numpy

In [ ]:
import numpy as np

# 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [11]:
import numpy as np
array=np.zeros(10)
print("An array of 10 zeros")
print(array)

An array of 10 zeros
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [12]:
import numpy as np
array=np.ones(10)*5
print("An array of 10 fives")
print(array)

An array of 10 fives
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [13]:
import numpy as np
array=np.arange(20,36,2)
print(array)


[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [14]:
import numpy as np
s=np.arange(0,9).reshape(3,3)
print(s)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


# 7. Concatinate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [17]:
import numpy as np
a=np.array([1,2,3])
b = np.array([4, 5, 6])
con=np.concatenate((a,b))
print(con)

[1 2 3 4 5 6]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [ ]:
import pandas as pd


In [5]:
import pandas as pd
import numpy as np
df['Color'] = ['blue','pink','violet']
df['Letter'] = ['b','p','v']
df = pd.DataFrame(data)
df


NameError: name 'df' is not defined

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [3]:
import pandas as pd 
a=pd.date_range(start='1-1-2023',end='10-2-2023',freq='2000H')
print(a)

DatetimeIndex(['2023-01-01 00:00:00', '2023-03-25 08:00:00',
               '2023-06-16 16:00:00', '2023-09-08 00:00:00'],
              dtype='datetime64[ns]', freq='2000H')


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [1]:
import pandas as pd 
lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]
data=(lists)
df=pd.DataFrame(lists)
print(df)

   0    1   2
0  1  aaa  22
1  2  bbb  25
2  3  ccc  24
